USE quantifyq;
INSERT INTO productos (nombre, descripcion, unidades_disponibles) VALUES
('Arroz', 'Arroz blanco de grano largo', 50),
('Frijoles', 'Frijoles rojos empacados', 40),
('Pasta', 'Pasta tipo espagueti', 30),
('Aceite', 'Aceite vegetal 1 litro', 20),
('Sal', 'Sal de mesa refinada', 100),
('Azúcar', 'Azúcar blanca granulada', 60),
('Harina', 'Harina de trigo fortificada', 45),
('Pan', 'Pan blanco de molde', 35),
('Leche', 'Leche entera en caja', 25),
('Huevos', 'Docena de huevos frescos', 30),
('Pollo', 'Pechuga de pollo congelada', 15),
('Carne de res', 'Carne molida especial', 10),
('Queso', 'Queso fresco tipo mozzarella', 20),
('Jugo', 'Jugo natural de naranja', 18),
('Manzanas', 'Manzanas rojas frescas', 22),
('Bananas', 'Bananas maduras', 25),
('Tomates', 'Tomates para ensalada', 28),
('Cebolla', 'Cebolla blanca', 32),
('Papas', 'Papas medianas para cocinar', 40),
('Atún', 'Lata de atún en agua', 50);
